# Generated by Django 6.0.3 on 2026-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='DRF, PostgreSQL, Celery, pytest etc.', max_length=400)),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True, help_text='Live Project link if deployed', null=True)),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='projects/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
